
const fs = require('fs');
    const constants = require('./helpers/constants')

    function calculateStatistics(uploadFolder) {
        const services = {
          'pdfToWord': 'pdf-to-word',
          'compressed': 'compress-pdf',
          'encrypted': 'password-protect-pdf',
          'decrypted': 'unlock-pdf',
          'merged': 'merge-pdf',
          'txtToPdf': 'txt-to-pdf',
          'convertedFile': 'office-to-pdf',
          'pngToPdf': 'png-to-pdf',
          'outputJpgToPdf': 'jpg-to-pdf',
          'convertedTxt': 'pdf-to-text',
          'convertedHtml': 'html-to-pdf',
          'ocrFile': 'online-ocr',
        };
      
        const stats = {};
      
        // Read the contents of the upload folder
        const files = fs.readdirSync(uploadFolder);
      
        // Count files generated by each service
        for (const serviceName in services) {
          const serviceLabel = services[serviceName];
          const serviceCount = files.filter((file) => file.includes(serviceName)).length;
          stats[serviceLabel] = serviceCount;
        }
      
        return stats;
      }

    const getStatistics = () => {
        const { DEFAULT_FOLDER_PATH } = constants
      return calculateStatistics(DEFAULT_FOLDER_PATH);
    }

  module.exports = {
    getStatistics, 
}
