const servicesRoutingArray = [
    { locale: "en", name: "word-to-pdf", full: "word-to-pdf" },
    { locale: "de", name: "word-to-pdf", full: "/de/word-in-pdf" },
    { locale: "fr", name: "word-to-pdf", full: "/fr/word-en-pdf" },
    { locale: "es", name: "word-to-pdf", full: "/es/word-a-pdf" },
    { locale: "pt", name: "word-to-pdf", full: "/pt/word-para-pdf" },
    { locale: "ja", name: "word-to-pdf", full: "/ja/word-pdf" },
    { locale: "id", name: "word-to-pdf", full: "/id/word-ke-pdf" },
    { locale: "it", name: "word-to-pdf", full: "/it/da-word-a-pdf" },
    { locale: "mk", name: "word-to-pdf", full: "/mk/word-vo-pdf" },
    { locale: "tr", name: "word-to-pdf", full: "/tr/word-pdf-cevirme" },
    { locale: "ru", name: "word-to-pdf", full: "/ru/word-v-pdf" },
    { locale: "zh", name: "word-to-pdf", full: "/zh/word-pdf" },
    { locale: "uk", name: "word-to-pdf", full: "/uk/word-v-pdf" },
    { locale: "ms", name: "word-to-pdf", full: "/ms/word-kepada-pdf" },

    { locale: "en", name: "unlock-pdf", full: "unlock-pdf" },
    { locale: "de", name: "unlock-pdf", full: "/de/pdf-entsperren" },
    { locale: "fr", name: "unlock-pdf", full: "/fr/deverrouiller-pdf" },
    { locale: "es", name: "unlock-pdf", full: "/es/desbloquear-pdf" },
    { locale: "pt", name: "unlock-pdf", full: "/pt/desbloquear-pdf" },
    { locale: "ja", name: "unlock-pdf", full: "/ja/unlock-pdf" },
    { locale: "id", name: "unlock-pdf", full: "/id/buka-kunci-pdf" },
    { locale: "it", name: "unlock-pdf", full: "/it/sblocca-pdf" },
    { locale: "mk", name: "unlock-pdf", full: "/mk/otkluchi-pdf" },
    { locale: "ms", name: "unlock-pdf", full: "/ms/buka-kunci-pdf" },
    { locale: "tr", name: "unlock-pdf", full: "/tr/pdf-sifre-kaldirma" },
    { locale: "ru", name: "unlock-pdf", full: "/ru/razblokirovat-pdf" },
    { locale: "zh", name: "unlock-pdf", full: "/zh/unlock-pdf" },
    { locale: "uk", name: "unlock-pdf", full: "/uk/rozblokuvati-pdf" },

    { locale: "en", name: "compress-pdf", full: "compress-pdf" },
    { locale: "de", name: "compress-pdf", full: "/de/pdf-verkleinern" },
    { locale: "fr", name: "compress-pdf", full: "/fr/compresser-pdf" },
    { locale: "es", name: "compress-pdf", full: "/es/comprimir-pdf" },
    { locale: "pt", name: "compress-pdf", full: "/pt/comprimir-pdf" },
    { locale: "ja", name: "compress-pdf", full: "/ja/compress-pdf" },
    { locale: "id", name: "compress-pdf", full: "/id/kompres-pdf" },
    { locale: "it", name: "compress-pdf", full: "/it/comprimere-pdf" },
    { locale: "mk", name: "compress-pdf", full: "/mk/kompresiraj-pdf" },
    { locale: "ms", name: "compress-pdf", full: "/ms/mampatkan-pdf" },
    { locale: "tr", name: "compress-pdf", full: "/tr/pdf-kucultme" },
    { locale: "ru", name: "compress-pdf", full: "/ru/szhat-pdf" },
    { locale: "zh", name: "compress-pdf", full: "/zh/compress-pdf" },
    { locale: "uk", name: "compress-pdf", full: "/uk/stisnuti-pdf" },
    

    { locale: "en", name: "excel-to-pdf", full: "excel-to-pdf" },
    { locale: "de", name: "excel-to-pdf", full: "/de/excel-in-pdf" },
    { locale: "fr", name: "excel-to-pdf", full: "/fr/excel-en-pdf" },
    { locale: "es", name: "excel-to-pdf", full: "/es/excel-a-pdf" },
    { locale: "pt", name: "excel-to-pdf", full: "/pt/excel-para-pdf" },
    { locale: "ja", name: "excel-to-pdf", full: "/ja/excel-pdf" },
    { locale: "id", name: "excel-to-pdf", full: "/id/excel-ke-pdf" },
    { locale: "it", name: "excel-to-pdf", full: "/it/da-excel-a-pdf" },
    { locale: "mk", name: "excel-to-pdf", full: "/mk/excel-vo-pdf" },
    { locale: "ms", name: "excel-to-pdf", full: "/ms/excel-kepada-pdf" },
    { locale: "tr", name: "excel-to-pdf", full: "/tr/excel-pdf-cevirme" },
    { locale: "ru", name: "excel-to-pdf", full: "/ru/excel-v-pdf" },
    { locale: "zh", name: "excel-to-pdf", full: "/zh/excel-pdf" },
    { locale: "uk", name: "excel-to-pdf", full: "/uk/excel-v-pdf" },

    { locale: "en", name: "html-to-pdf", full: "html-to-pdf" },
    { locale: "de", name: "html-to-pdf", full: "/de/html-in-pdf" },
    { locale: "fr", name: "html-to-pdf", full: "/fr/html-en-pdf" },
    { locale: "es", name: "html-to-pdf", full: "/es/html-a-pdf" },
    { locale: "pt", name: "html-to-pdf", full: "/pt/html-para-pdf" },
    { locale: "ja", name: "html-to-pdf", full: "/ja/html-pdf" },
    { locale: "id", name: "html-to-pdf", full: "/id/html-ke-pdf" },
    { locale: "it", name: "html-to-pdf", full: "/it/da-html-a-pdf" },
    { locale: "mk", name: "html-to-pdf", full: "/mk/html-vo-pdf" },
    { locale: "ms", name: "html-to-pdf", full: "/ms/html-kepada-pdf" },
    { locale: "tr", name: "html-to-pdf", full: "/tr/html-pdf-cevirme" },
    { locale: "ru", name: "html-to-pdf", full: "/ru/html-v-pdf" },
    { locale: "zh", name: "html-to-pdf", full: "/zh/html-pdf" },
    { locale: "uk", name: "html-to-pdf", full: "/uk/html-v-pdf" },

    { locale: "en", name: "jpg-to-pdf", full: "jpg-to-pdf" },
    { locale: "de", name: "jpg-to-pdf", full: "/de/jpg-in-pdf" },
    { locale: "fr", name: "jpg-to-pdf", full: "/fr/jpg-en-pdf" },
    { locale: "es", name: "jpg-to-pdf", full: "/es/jpg-a-pdf" },
    { locale: "pt", name: "jpg-to-pdf", full: "/pt/jpg-para-pdf" },
    { locale: "ja", name: "jpg-to-pdf", full: "/ja/jpg-pdf" },
    { locale: "id", name: "jpg-to-pdf", full: "/id/jpg-ke-pdf" },
    { locale: "it", name: "jpg-to-pdf", full: "/it/da-jpg-a-pdf" },
    { locale: "mk", name: "jpg-to-pdf", full: "/mk/jpg-vo-pdf" },
    { locale: "ms", name: "jpg-to-pdf", full: "/ms/jpg-kepada-pdf" },
    { locale: "tr", name: "jpg-to-pdf", full: "/tr/jpg-pdf-cevirme" },
    { locale: "ru", name: "jpg-to-pdf", full: "/ru/jpg-v-pdf" },
    { locale: "zh", name: "jpg-to-pdf", full: "/zh/jpg-pdf" },
    { locale: "uk", name: "jpg-to-pdf", full: "/uk/jpg-to-pdf" },

    { locale: "en", name: "merge-pdf", full: "merge-pdf" },
    { locale: "de", name: "merge-pdf", full: "/de/pdf-zusammenfuhren" },
    { locale: "fr", name: "merge-pdf", full: "/fr/fusionner-pdf" },
    { locale: "es", name: "merge-pdf", full: "/es/fusionar-pdf" },
    { locale: "pt", name: "merge-pdf", full: "/pt/mesclar-pdf" },
    { locale: "ja", name: "merge-pdf", full: "/ja/pdf-merge" },
    { locale: "id", name: "merge-pdf", full: "/id/gabung-pdf" },
    { locale: "it", name: "merge-pdf", full: "/it/unisci-pdf" },
    { locale: "mk", name: "merge-pdf", full: "/mk/kombiniraj-pdf" },
    { locale: "ms", name: "merge-pdf", full: "/ms/gabungkan-pdf" },
    { locale: "tr", name: "merge-pdf", full: "/tr/pdf-birlestirme" },
    { locale: "ru", name: "merge-pdf", full: "/ru/obedinit-pdf" },
    { locale: "zh", name: "merge-pdf", full: "/zh/pdf-merge" },
    { locale: "uk", name: "merge-pdf", full: "/uk/merge-pdf" },

    { locale: "en", name: "odp-to-pdf", full: "odp-to-pdf" },
    { locale: "de", name: "odp-to-pdf", full: "/de/odp-in-pdf" },
    { locale: "fr", name: "odp-to-pdf", full: "/fr/odp-en-pdf" },
    { locale: "es", name: "odp-to-pdf", full: "/es/odp-a-pdf" },
    { locale: "pt", name: "odp-to-pdf", full: "/pt/odp-para-pdf" },
    { locale: "ja", name: "odp-to-pdf", full: "/ja/odp-pdf" },
    { locale: "id", name: "odp-to-pdf", full: "/id/odp-ke-pdf" },
    { locale: "it", name: "odp-to-pdf", full: "/it/da-odp-a-pdf" },
    { locale: "mk", name: "odp-to-pdf", full: "/mk/odp-vo-pdf" },
    { locale: "ms", name: "odp-to-pdf", full: "/ms/odp-kepada-pdf" },
    { locale: "tr", name: "odp-to-pdf", full: "/tr/odp-pdf-cevirme" },
    { locale: "ru", name: "odp-to-pdf", full: "/ru/odp-v-pdf" },
    { locale: "zh", name: "odp-to-pdf", full: "/zh/odp-pdf" },
    { locale: "uk", name: "odp-to-pdf", full: "/uk/odp-v-pdf" },

    { locale: "en", name: "ods-to-pdf", full: "ods-to-pdf" },
    { locale: "de", name: "ods-to-pdf", full: "/de/ods-in-pdf" },
    { locale: "fr", name: "ods-to-pdf", full: "/fr/ods-en-pdf" },
    { locale: "es", name: "ods-to-pdf", full: "/es/ods-a-pdf" },
    { locale: "pt", name: "ods-to-pdf", full: "/pt/ods-para-pdf" },
    { locale: "ja", name: "ods-to-pdf", full: "/ja/ods-pdf" },
    { locale: "id", name: "ods-to-pdf", full: "/id/ods-ke-pdf" },
    { locale: "it", name: "ods-to-pdf", full: "/it/da-ods-a-pdf" },
    { locale: "mk", name: "ods-to-pdf", full: "/mk/ods-vo-pdf" },
    { locale: "ms", name: "ods-to-pdf", full: "/ms/ods-kepada-pdf" },
    { locale: "tr", name: "ods-to-pdf", full: "/tr/ods-pdf-cevirme" },
    { locale: "ru", name: "ods-to-pdf", full: "/ru/ods-v-pdf" },
    { locale: "zh", name: "ods-to-pdf", full: "/zh/ods-pdf" },
    { locale: "uk", name: "ods-to-pdf", full: "/uk/ods-v-pdf" },

    { locale: "en", name: "txt-to-pdf", full: "txt-to-pdf" },
    { locale: "de", name: "txt-to-pdf", full: "/de/txt-in-pdf" },
    { locale: "fr", name: "txt-to-pdf", full: "/fr/txt-en-pdf" },
    { locale: "es", name: "txt-to-pdf", full: "/es/txt-a-pdf" },
    { locale: "pt", name: "txt-to-pdf", full: "/pt/txt-para-pdf" },
    { locale: "ja", name: "txt-to-pdf", full: "/ja/txt-pdf" },
    { locale: "id", name: "txt-to-pdf", full: "/id/txt-ke-pdf" },
    { locale: "it", name: "txt-to-pdf", full: "/it/da-txt-a-pdf" },
    { locale: "mk", name: "txt-to-pdf", full: "/mk/tekst-vo-pdf" },
    { locale: "ms", name: "txt-to-pdf", full: "/ms/txt-to-pdf" },
    { locale: "tr", name: "txt-to-pdf", full: "/tr/txt-pdf-cevirme" },
    { locale: "ru", name: "txt-to-pdf", full: "/ru/txt-v-pdf" },
    { locale: "zh", name: "txt-to-pdf", full: "/zh/txt-pdf" },
    { locale: "uk", name: "txt-to-pdf", full: "/uk/txt-to-pdf" },

    { locale: "en", name: "ppt-to-pdf", full: "ppt-to-pdf" },
    { locale: "de", name: "ppt-to-pdf", full: "/de/ppt-in-pdf" },
    { locale: "fr", name: "ppt-to-pdf", full: "/fr/ppt-en-pdf" },
    { locale: "es", name: "ppt-to-pdf", full: "/es/ppt-a-pdf" },
    { locale: "pt", name: "ppt-to-pdf", full: "/pt/ppt-para-pdf" },
    { locale: "ja", name: "ppt-to-pdf", full: "/ja/ppt-pdf" },
    { locale: "id", name: "ppt-to-pdf", full: "/id/ppt-ke-pdf" },
    { locale: "it", name: "ppt-to-pdf", full: "/it/da-ppt-a-pdf" },
    { locale: "mk", name: "ppt-to-pdf", full: "/mk/ppt-vo-pdf" },
    { locale: "ms", name: "ppt-to-pdf", full: "/ms/ppt-kepada-pdf" },
    { locale: "tr", name: "ppt-to-pdf", full: "/tr/ppt-pdf-cevirme" },
    { locale: "ru", name: "ppt-to-pdf", full: "/ru/ppt-v-pdf" },
    { locale: "zh", name: "ppt-to-pdf", full: "/zh/ppt-pdf" },
    { locale: "uk", name: "ppt-to-pdf", full: "/uk/ppt-v-pdf" },

    { locale: "en", name: "png-to-pdf", full: "png-to-pdf" },
    { locale: "de", name: "png-to-pdf", full: "/de/png-in-pdf" },
    { locale: "fr", name: "png-to-pdf", full: "/fr/png-en-pdf" },
    { locale: "es", name: "png-to-pdf", full: "/es/png-a-pdf" },
    { locale: "pt", name: "png-to-pdf", full: "/pt/png-para-pdf" },
    { locale: "ja", name: "png-to-pdf", full: "/ja/png-pdf" },
    { locale: "id", name: "png-to-pdf", full: "/id/png-ke-pdf" },
    { locale: "it", name: "png-to-pdf", full: "/it/da-png-a-pdf" },
    { locale: "mk", name: "png-to-pdf", full: "/mk/png-vo-pdf" },
    { locale: "ms", name: "png-to-pdf", full: "/ms/png-kepada-pdf" },
    { locale: "tr", name: "png-to-pdf", full: "/tr/png-pdf-cevirme" },
    { locale: "ru", name: "png-to-pdf", full: "/ru/png-v-pdf" },
    { locale: "zh", name: "png-to-pdf", full: "/zh/png-pdf" },
    { locale: "uk", name: "png-to-pdf", full: "/uk/png-to-pdf" },
    
    { locale: "en", name: "pdf-to-word", full: "pdf-to-word" },
    { locale: "de", name: "pdf-to-word", full: "/de/pdf-in-word" },
    { locale: "fr", name: "pdf-to-word", full: "/fr/pdf-en-word" },
    { locale: "es", name: "pdf-to-word", full: "/es/pdf-a-word" },
    { locale: "pt", name: "pdf-to-word", full: "/pt/pdf-para-word" },
    { locale: "ja", name: "pdf-to-word", full: "/ja/pdf-word" },
    { locale: "id", name: "pdf-to-word", full: "/id/pdf-ke-word" },
    { locale: "it", name: "pdf-to-word", full: "/it/da-pdf-a-word" },
    { locale: "mk", name: "pdf-to-word", full: "/mk/pdf-vo-word" },
    { locale: "ms", name: "pdf-to-word", full: "/ms/pdf-ke-perkataan" },
    { locale: "tr", name: "pdf-to-word", full: "/tr/pdf-word" },
    { locale: "ru", name: "pdf-to-word", full: "/ru/pdf-v-word" },
    { locale: "zh", name: "pdf-to-word", full: "/zh/pdf-word" },
    { locale: "uk", name: "pdf-to-word", full: "/uk/pdf-to-word" },

    { locale: "en", name: "pdf-to-text", full: "pdf-to-text" },
    { locale: "de", name: "pdf-to-text", full: "/de/pdf-in-text" },
    { locale: "fr", name: "pdf-to-text", full: "/fr/pdf-en-text" },
    { locale: "es", name: "pdf-to-text", full: "/es/pdf-a-text" },
    { locale: "pt", name: "pdf-to-text", full: "/pt/pdf-para-text" },
    { locale: "ja", name: "pdf-to-text", full: "/ja/pdf-text" },
    { locale: "id", name: "pdf-to-text", full: "/id/pdf-ke-teks" },
    { locale: "it", name: "pdf-to-text", full: "/it/da-pdf-a-txt" },
    { locale: "mk", name: "pdf-to-text", full: "/mk/pdf-vo-tekst" },
    { locale: "ms", name: "pdf-to-text", full: "/ms/pdf-to-text" },
    { locale: "tr", name: "pdf-to-text", full: "/tr/pdf-text-cevirme" },
    { locale: "ru", name: "pdf-to-text", full: "/ru/pdf-v-txt" },
    { locale: "zh", name: "pdf-to-text", full: "/zh/pdf-txt" },
    { locale: "uk", name: "pdf-to-text", full: "/uk/pdf-to-text" },

    { locale: "en", name: "pdf-reader", full: "pdf-reader" },
    { locale: "de", name: "pdf-reader", full: "/de/pdf-reader" },
    { locale: "fr", name: "pdf-reader", full: "/fr/lecteur-pdf" },
    { locale: "es", name: "pdf-reader", full: "/es/lector-pdf" },
    { locale: "pt", name: "pdf-reader", full: "/pt/leitor-de-pdf" },
    { locale: "ja", name: "pdf-reader", full: "/ja/pdf-reader" },
    { locale: "id", name: "pdf-reader", full: "/id/pembaca-pdf" },
    { locale: "it", name: "pdf-reader", full: "/it/lettore-pdf" },
    { locale: "mk", name: "pdf-reader", full: "/mk/pdf-rider" },
    { locale: "ms", name: "pdf-reader", full: "/ms/pembaca-pdf" },
    { locale: "tr", name: "pdf-reader", full: "/tr/pdf-okuyucu" },
    { locale: "ru", name: "pdf-reader", full: "/ru/chitatel-pdf" },
    { locale: "zh", name: "pdf-reader", full: "/zh/pdf-viewer" },
    { locale: "uk", name: "pdf-reader", full: "/uk/pdf-reader" },

    // { locale: "en", name: "pdf-editor", full: "pdf-editor" },
    // { locale: "de", name: "pdf-editor", full: "/de/pdf-editor" },
    // { locale: "fr", name: "pdf-editor", full: "/fr/pdf-editor" },
    // { locale: "es", name: "pdf-editor", full: "/es/pdf-editor" },
    // { locale: "pt", name: "pdf-editor", full: "/pt/pdf-editor" },
    // { locale: "ja", name: "pdf-editor", full: "/ja/pdf-editor" },
    // { locale: "id", name: "pdf-editor", full: "/id/pdf-editor" },
    // { locale: "it", name: "pdf-editor", full: "/it/pdf-editor" },
    // { locale: "mk", name: "pdf-editor", full: "/mk/pdf-editor" },
    // { locale: "tr", name: "pdf-editor", full: "/tr/pdf-editor" },
    // { locale: "ru", name: "pdf-editor", full: "/ru/pdf-editor" },
    // { locale: "zh", name: "pdf-editor", full: "/zh/pdf-editor" },

    { locale: "en", name: "password-protect-pdf", full: "password-protect-pdf" },
    { locale: "de", name: "password-protect-pdf", full: "/de/pdf-verschlusseln" },
    { locale: "fr", name: "password-protect-pdf", full: "/fr/proteger-pdf" },
    { locale: "es", name: "password-protect-pdf", full: "/es/proteger-pdf" },
    { locale: "pt", name: "password-protect-pdf", full: "/pt/proteger-pdf" },
    { locale: "ja", name: "password-protect-pdf", full: "/ja/protect-pdf" },
    { locale: "id", name: "password-protect-pdf", full: "/id/proteksi-kata-sandi-pdf" },
    { locale: "it", name: "password-protect-pdf", full: "/it/proteggi-pdf" },
    { locale: "mk", name: "password-protect-pdf", full: "/mk/pdf-enkripcija" },
    { locale: "ms", name: "password-protect-pdf", full: "/ms/kata-laluan-lindungi-pdf" },
    { locale: "tr", name: "password-protect-pdf", full: "/tr/korumali-pdf" },
    { locale: "ru", name: "password-protect-pdf", full: "/ru/zashhitit-parolem-pdf" },
    { locale: "zh", name: "password-protect-pdf", full: "/zh/protect-pdf" },
    { locale: "uk", name: "password-protect-pdf", full: "/uk/zashhitit-pdf" },

    { locale: "en", name: "online-ocr", full: "online-ocr" },
    { locale: "de", name: "online-ocr", full: "/de/online-ocr" },
    { locale: "fr", name: "online-ocr", full: "/fr/ocr-en-ligne" },
    { locale: "es", name: "online-ocr", full: "/es/ocr-en-linea" },
    { locale: "pt", name: "online-ocr", full: "/pt/ocr-online" },
    { locale: "ja", name: "online-ocr", full: "/ja/ocr-online" },
    { locale: "id", name: "online-ocr", full: "/id/online-ocr" },
    { locale: "it", name: "online-ocr", full: "/it/online-ocr" },
    { locale: "mk", name: "online-ocr", full: "/mk/konvertor-na-slika-vo-tekst" },
    { locale: "ms", name: "online-ocr", full: "/ms/ocr-dalam-talian" },
    { locale: "tr", name: "online-ocr", full: "/tr/cevrimici-ocr" },
    { locale: "ru", name: "online-ocr", full: "/ru/servisy-dlya-raspoznavaniya-teksta" },
    { locale: "zh", name: "online-ocr", full: "/zh/ocr" },
    { locale: "uk", name: "online-ocr", full: "/uk/online-ocr" },

    { locale: "en", name: "odt-to-pdf", full: "odt-to-pdf" },
    { locale: "de", name: "odt-to-pdf", full: "/de/odt-in-pdf" },
    { locale: "fr", name: "odt-to-pdf", full: "/fr/odt-en-pdf" },
    { locale: "es", name: "odt-to-pdf", full: "/es/odt-a-pdf" },
    { locale: "pt", name: "odt-to-pdf", full: "/pt/odt-para-pdf" },
    { locale: "ja", name: "odt-to-pdf", full: "/ja/odt-pdf" },
    { locale: "id", name: "odt-to-pdf", full: "/id/odt-ke-pdf" },
    { locale: "it", name: "odt-to-pdf", full: "/it/da-odt-a-pdf" },
    { locale: "mk", name: "odt-to-pdf", full: "/mk/odt-vo-pdf" },
    { locale: "ms", name: "odt-to-pdf", full: "/ms/odt-kepada-pdf" },
    { locale: "tr", name: "odt-to-pdf", full: "/tr/odt-pdf-cevirme" },
    { locale: "ru", name: "odt-to-pdf", full: "/ru/odt-v-pdf" },
    { locale: "zh", name: "odt-to-pdf", full: "/zh/odt-pdf" },
    { locale: "uk", name: "odt-to-pdf", full: "/uk/odt-v-pdf" },

]

const staticRoutingArray = [
    { locale: "en", name: "index", full: "/" },
    { locale: "de", name: "index", full: "de" },
    { locale: "fr", name: "index", full: "fr" },
    { locale: "es", name: "index", full: "es" },
    { locale: "pt", name: "index", full: "pt" },
    { locale: "ja", name: "index", full: "ja" },
    { locale: "ru", name: "index", full: "ru" },
    { locale: "mk", name: "index", full: "mk" },
    { locale: "it", name: "index", full: "it" },
    { locale: "id", name: "index", full: "id" },
    { locale: "tr", name: "index", full: "tr" },
    { locale: "zh", name: "index", full: "zh" },
    { locale: "uk", name: "index", full: "uk" },
    { locale: "ms", name: "index", full: "ms" },

    { locale: "en", name: "error", full: "/" },
    { locale: "de", name: "error", full: "de/error" },
    { locale: "fr", name: "error", full: "fr/error" },
    { locale: "es", name: "error", full: "es/error" },
    { locale: "pt", name: "error", full: "pt/error" },
    { locale: "ja", name: "error", full: "ja/error" },
    { locale: "ru", name: "error", full: "ru/error" },
    { locale: "mk", name: "error", full: "mk/error" },
    { locale: "it", name: "error", full: "it/error" },
    { locale: "id", name: "error", full: "id/error" },
    { locale: "tr", name: "error", full: "tr/error" },
    { locale: "zh", name: "error", full: "zh/error" },
    { locale: "uk", name: "error", full: "uk/error" },
    { locale: "ms", name: "error", full: "ms/error" },

    { locale: "en", name: "about", full: "about" },
    { locale: "de", name: "about", full: "/de/uber-uns" },
    { locale: "fr", name: "about", full: "/fr/a-propos" },
    { locale: "es", name: "about", full: "/es/acerca" },
    { locale: "pt", name: "about", full: "/pt/sobre" },
    { locale: "ja", name: "about", full: "/ja/about" },
    { locale: "id", name: "about", full: "/id/tentang" },
    { locale: "it", name: "about", full: "/it/about" },
    { locale: "mk", name: "about", full: "/mk/za-nas" },
    { locale: "tr", name: "about", full: "/tr/about" },
    { locale: "ru", name: "about", full: "/ru/about" },
    { locale: "zh", name: "about", full: "/zh/about" },
    { locale: "uk", name: "about", full: "/uk/about" },
    { locale: "ms", name: "about", full: "/ms/about" },
    
    { locale: "en", name: "contact", full: "contact" },
    { locale: "de", name: "contact", full: "/de/kontakt" },
    { locale: "fr", name: "contact", full: "/fr/contacter" },
    { locale: "es", name: "contact", full: "/es/contactanos" },
    { locale: "pt", name: "contact", full: "/pt/entre-em-contato" },
    { locale: "ja", name: "contact", full: "/ja/contact" },
    { locale: "id", name: "contact", full: "/id/kontak" },
    { locale: "it", name: "contact", full: "/it/contact" },
    { locale: "mk", name: "contact", full: "/mk/contact" },
    { locale: "tr", name: "contact", full: "/tr/contact" },
    { locale: "ru", name: "contact", full: "/ru/contact" },
    { locale: "zh", name: "contact", full: "/zh/contact" },
    { locale: "uk", name: "contact", full: "/uk/contact" },
    { locale: "ms", name: "contact", full: "/ms/hubungi-kami" },

    { locale: "en", name: "terms-and-conditions", full: "terms-and-conditions" },
    { locale: "de", name: "terms-and-conditions", full: "/de/nutzungsbedingungen" },
    { locale: "fr", name: "terms-and-conditions", full: "/fr/conditions-util" },
    { locale: "es", name: "terms-and-conditions", full: "/es/terminos-de-uso" },
    { locale: "pt", name: "terms-and-conditions", full: "/pt/termos" },
    { locale: "ja", name: "terms-and-conditions", full: "/ja/terms" },
    { locale: "id", name: "terms-and-conditions", full: "/id/syarat-dan-ketentuan" },
    { locale: "it", name: "terms-and-conditions", full: "/it/termini-e-condizioni" },
    { locale: "mk", name: "terms-and-conditions", full: "/mk/uslovi-za-koristenje" },
    { locale: "tr", name: "terms-and-conditions", full: "/tr/terms" },
    { locale: "ru", name: "terms-and-conditions", full: "/ru/terms" },
    { locale: "zh", name: "terms-and-conditions", full: "/zh/terms" },
    { locale: "uk", name: "terms-and-conditions", full: "/uk/terms" },
    { locale: "ms", name: "terms-and-conditions", full: "/ms/terms" },
    

    { locale: "en", name: "privacy-policy", full: "privacy-policy" },
    { locale: "de", name: "privacy-policy", full: "/de/richtlinien-fur-den-datenschutz" },
    { locale: "fr", name: "privacy-policy", full: "/fr/politique-de-confidentialite" },
    { locale: "es", name: "privacy-policy", full: "/es/politica-de-privacidad" },
    { locale: "pt", name: "privacy-policy", full: "/pt/privacidade" },
    { locale: "ja", name: "privacy-policy", full: "/ja/privacy" },
    { locale: "id", name: "privacy-policy", full: "/id/kebijakan-pribadi" },
    { locale: "it", name: "privacy-policy", full: "/it/privacy" },
    { locale: "mk", name: "privacy-policy", full: "/mk/politika-za-privatnost" },
    { locale: "tr", name: "privacy-policy", full: "/tr/privacy" },
    { locale: "ru", name: "privacy-policy", full: "/ru/privacy" },
    { locale: "zh", name: "privacy-policy", full: "/zh/privacy" },
    { locale: "uk", name: "privacy-policy", full: "/uk/privacy" },
    { locale: "ms", name: "privacy-policy", full: "/ms/privasi" },

    { locale: "en", name: "careers", full: "careers" },
    { locale: "en", name: "job1", full: "/careers/back-end-developer-intern-nodejs" },
    { locale: "en", name: "job2", full: "/careers/brand-marketing-intern" },

    { locale: "en", name: "sitemap", full: "sitemap" },
    { locale: "de", name: "sitemap", full: "/de/sitemap" },
    { locale: "fr", name: "sitemap", full: "/fr/sitemap" },
    { locale: "es", name: "sitemap", full: "/es/sitemap" },
    { locale: "pt", name: "sitemap", full: "/pt/sitemap" },
    { locale: "ja", name: "sitemap", full: "/ja/sitemap" },
    { locale: "id", name: "sitemap", full: "/id/sitemap" },
    { locale: "it", name: "sitemap", full: "/it/sitemap" },
    { locale: "mk", name: "sitemap", full: "/mk/sitemap" },
    { locale: "tr", name: "sitemap", full: "/tr/sitemap" },
    { locale: "ru", name: "sitemap", full: "/ru/sitemap" },
    { locale: "zh", name: "sitemap", full: "/zh/sitemap" },
    { locale: "uk", name: "sitemap", full: "/uk/sitemap" },
    { locale: "ms", name: "sitemap", full: "/ms/sitemap" },
]
const allowedPaths=['fonts','views','img','javascripts','stylesheets'];

  exports.servicesRoutingArray = servicesRoutingArray;
  exports.staticRoutingArray = staticRoutingArray;
  exports.allowedPaths= allowedPaths;